version: '3.9'

services:
  main:
    container_name: main
    build:
      context: ./server
      target: development
    volumes:
      - /usr/src/app
      - /usr/src/app/node_modules
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
      - 9229:9229
    command: npm run start:dev
    env_file:
      - .env